# Generated by Django 4.0.6 on 2022-07-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drink',
            table='drinks',
        ),
    ]
